---
name: Test

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.y?ml'
      - '*.js'
  push:
    paths:
      - '**/*.js'
      - '**/*.y?ml'
      - '*.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
